"""Category labels for Food-101 class names. Used for insights, not nutrition values."""

FOOD_CATEGORIES: dict[str, str] = {
    "apple_pie": "dessert",
    "baby_back_ribs": "meat",
    "baklava": "dessert",
    "beef_carpaccio": "meat",
    "beef_tartare": "meat",
    "beet_salad": "salad",
    "beignets": "fried",
    "bibimbap": "grain",
    "bread_pudding": "dessert",
    "breakfast_burrito": "breakfast",
    "bruschetta": "appetizer",
    "caesar_salad": "salad",
    "cannoli": "dessert",
    "caprese_salad": "salad",
    "carrot_cake": "dessert",
    "ceviche": "seafood",
    "cheesecake": "dessert",
    "cheese_plate": "dairy",
    "chicken_curry": "meat",
    "chicken_quesadilla": "meat",
    "chicken_wings": "fried",
    "chocolate_cake": "dessert",
    "chocolate_mousse": "dessert",
    "churros": "fried",
    "clam_chowder": "soup",
    "club_sandwich": "sandwich",
    "crab_cakes": "seafood",
    "creme_brulee": "dessert",
    "croque_madame": "breakfast",
    "cup_cakes": "dessert",
    "deviled_eggs": "breakfast",
    "donuts": "fried",
    "dumplings": "grain",
    "edamame": "vegetable",
    "eggs_benedict": "breakfast",
    "escargots": "seafood",
    "falafel": "fried",
    "filet_mignon": "meat",
    "fish_and_chips": "fried",
    "foie_gras": "meat",
    "french_fries": "fried",
    "french_onion_soup": "soup",
    "french_toast": "breakfast",
    "fried_calamari": "fried",
    "fried_rice": "grain",
    "frozen_yogurt": "dessert",
    "garlic_bread": "grain",
    "gnocchi": "grain",
    "greek_salad": "salad",
    "grilled_cheese_sandwich": "sandwich",
    "grilled_salmon": "seafood",
    "guacamole": "vegetable",
    "gyoza": "grain",
    "hamburger": "sandwich",
    "hot_and_sour_soup": "soup",
    "hot_dog": "sandwich",
    "huevos_rancheros": "breakfast",
    "hummus": "vegetable",
    "ice_cream": "dessert",
    "lasagna": "grain",
    "lobster_bisque": "soup",
    "lobster_roll_sandwich": "sandwich",
    "macaroni_and_cheese": "grain",
    "macarons": "dessert",
    "miso_soup": "soup",
    "mussels": "seafood",
    "nachos": "appetizer",
    "omelette": "breakfast",
    "onion_rings": "fried",
    "oysters": "seafood",
    "pad_thai": "grain",
    "paella": "grain",
    "pancakes": "breakfast",
    "panna_cotta": "dessert",
    "peking_duck": "meat",
    "pho": "soup",
    "pizza": "grain",
    "pork_chop": "meat",
    "poutine": "fried",
    "prime_rib": "meat",
    "pulled_pork_sandwich": "sandwich",
    "ramen": "soup",
    "ravioli": "grain",
    "red_velvet_cake": "dessert",
    "risotto": "grain",
    "samosa": "fried",
    "sashimi": "seafood",
    "scallops": "seafood",
    "seaweed_salad": "salad",
    "shrimp_and_grits": "seafood",
    "spaghetti_bolognese": "grain",
    "spaghetti_carbonara": "grain",
    "spring_rolls": "fried",
    "steak": "meat",
    "strawberry_shortcake": "dessert",
    "sushi": "seafood",
    "tacos": "grain",
    "takoyaki": "seafood",
    "tiramisu": "dessert",
    "tuna_tartare": "seafood",
    "waffles": "breakfast",
}

VEGETABLE_FOODS = {
    "beet_salad",
    "caesar_salad",
    "caprese_salad",
    "edamame",
    "greek_salad",
    "guacamole",
    "hummus",
    "seaweed_salad",
}

FRIED_FOODS = {
    "beignets",
    "chicken_wings",
    "churros",
    "donuts",
    "falafel",
    "fish_and_chips",
    "french_fries",
    "fried_calamari",
    "onion_rings",
    "poutine",
    "samosa",
    "spring_rolls",
}

HIGH_PROTEIN_FOODS = {
    "baby_back_ribs",
    "beef_carpaccio",
    "beef_tartare",
    "chicken_curry",
    "edamame",
    "eggs_benedict",
    "filet_mignon",
    "grilled_salmon",
    "omelette",
    "pork_chop",
    "prime_rib",
    "sashimi",
    "scallops",
    "steak",
    "tuna_tartare",
}


def display_name(food_name: str) -> str:
    return food_name.replace("_", " ").title()


def category_for(food_name: str) -> str:
    return FOOD_CATEGORIES.get(food_name, "other")
